import getCurrentUser from "./actions/getCurrentUser";
import NavBar from "./components/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body className={`flex flex-col ${inter.className}`}>
        <NavBar user={user}></NavBar>
        <main className="p-6 grow">{children}</main>
      </body>
    </html>
  );
}
